### ISSUE TITLE
How to use without use_frameworks! ie without dynamic frameworks

### ISSUE THREAD

**Issue by kishoretheju** [CleverTap/CTNotificationService#6]
Cannot use use_frameworks! in my project because one of the depdancies of react native does not support it and i am getting the following error as a result of it. How to fix it, any workarounds?
<img width="1012" alt="screenshot 2018-11-19 at 5 36 09 pm" src="https://user-images.githubusercontent.com/6185202/48706298-d7005800-ec21-11e8-8e29-2a08cbfcba6d.png">

**Comment by Aditi3** [comment]
Hey @kishoretheju 

The **use_frameworks** option tells CocoaPods to use frameworks instead of static libraries. Since **Swift** doesn't support Static Libraries you have to use frameworks. 

If you're using Swift for coding and **use_frameworks** is creating conflicts in your application, I would recommend to manually integrate our library.

**Comment by kishoretheju** [comment]
Thank you, integrated it manually.

**Comment by 3KINGZ** [comment]
@kishoretheju how do you integrate the library manually?

**Comment by 3KINGZ** [comment]
> @kishoretheju how do you integrate the library manually? i'm also using react-native and getting the same issue as you
